general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
padding = { x = 5, y = 5 }
dynamic_padding = true
opacity = 0.9

[terminal]
shell = "/bin/zsh"

[colors]
transparent_background_colors = true
